language: c

cache:
  directories:
    - $HOME/local

sudo: required

matrix:
  include:
    - compiler: gcc
      env:
    - compiler: gcc
      env: T_INSTALL=t ARGS=--with-test-installed
    - compiler: clang
      env: CC=clang CXX=clang++

addons:
  apt:
    sources:
    packages:
      - libelf-dev
      - libboost-dev
      - libgcrypt-dev
      - munge
      - build-essential
      - pkg-config
      - autoconf-archive

before_install:
  - eval $(./test/src/travis-dep-builder.sh --printenv)
  - ./test/src/travis-dep-builder.sh --cachedir=$HOME/local/.cache

script:
 - export MAKECMDS="make -j3 && make -j3 check"
 - ./bootstrap && mkdir build && cd build 
 - if test "$T_INSTALL" = "t" ; then ARGS="$ARGS --prefix=/tmp/lmon"; MAKECMDS="make -j3 && make install && make -j3 check"; fi
 - ../configure --with-test-rm=orte $ARGS --with-test-rm-launcher=$HOME/local/bin/mpirun --with-test-ncore-per-CN=2 --with-test-nnodes=1
 - eval ${MAKECMDS}
 - if test "$T_INSTALL" = "t"; then ../test/src/travis-run-test.sh; fi
